client_config_backend: settings
client_config:
  client_id: 324217495053-a3nmag66qqvtp7vah584461hui25l9gl.apps.googleusercontent.com
  client_secret: nbWQbOiNtTTkvjrdz-kSF5hZ

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
